fix: debug_task accepts *args **kwargs to prevent TypeError
The function was defined as debug_task(self) which caused:
  TypeError: debug_task() takes 1 positional argument but 2 were given
when called with apply_async(args=['Hello World']).

Fix: change signature to debug_task(self, *args, **kwargs)

Verified: all 25 bind=True tasks in the project have self as first arg.